; Fresh PlatformIO project configuration
; Set board/framework to your target hardware before building.

[env:demo_arm]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
lib_deps = adafruit/Adafruit NeoPixel
